### ISSUE TITLE
`MarkRead` is missing request body in request

### ISSUE THREAD

**Issue by TheBlueMatt** [mautrix/go#105]
The spec says you get a 400 if `thread_id` is invalid for some way, and when the imessage bridge tries to `MarkRead`, synapse says `synapse.http.server - 108 - INFO - POST-5463- <XForwardedForRequest at 0xpointer method='POST' uri='/_matrix/client/v3/rooms/REDACTED/receipt/m.read/REDACTED?user_id=@REDACTED' clientproto='HTTP/1.1' site='RED'> SynapseError: 400 - Content must be a JSON object.`

**Comment by tulir** [comment]
It was fixed (and included in a release) 2 weeks before you opened the issue
