### ISSUE TITLE
Log message: "Upserting row into user_batch_tokens"

### ISSUE THREAD

**Issue by jellersby** [mautrix/go#114]
Hello. Can anyone help me track down this log message? It's absolutely spamming my zerolog output and I don't know where it's coming from. I've searched this repo as well as my entire $GOPATH/pkg and I can't find where it's coming from. Thank you.
![Screenshot 2023-02-19 at 11 18 58 PM](https://user-images.githubusercontent.com/92661162/220038710-30f6b2c9-92dd-4dc8-9b18-d7e0b1303b79.png)

**Comment by tulir** [comment]
Probably your code, maybe copied from one of these places: https://github.com/search?q=user_batch_tokens&type=code

**Comment by jellersby** [comment]
Thank you, not sure how I missed that.
