### ISSUE TITLE
How can I find out which rooms I have been invited to?

### ISSUE THREAD

**Issue by flyingkukri** [mautrix/go#169]
Hi, I want my clients to be able to create and join private rooms. I can create private rooms. However, I couldn't find out how the web clients know that the have been invited to join a room. I also couldn't find out what kind of event gets sent upon an invite in the client-server API specification. Can you guys help me how to write a handler for invites?

**Comment by tulir** [comment]
GitHub issues are not the place for questions. [#matrix-dev:matrix.org](https://matrix.to/#/#matrix-dev:matrix.org) for general API/spec questions, [#maunium:maunium.net](https://matrix.to/#/#maunium:maunium.net) (mentioned in the readme) for questions about using mautrix-go specifically
