### ISSUE TITLE
Encryption keys only send to one session

### ISSUE THREAD

**Issue by Ondolin** [mautrix/go#37]
I have a problem with the encryption keys. When I send an encrypted message with this sdk using basically [this code](https://mau.dev/-/snippets/6), the encryption keys won't go to all of my devices. e.g. my phone can only decrypt the message if my desktop client is open. Is there a way to send the keys to all of my sessions and not only to one?

**Comment by CubicrootXYZ** [comment]
I am stuck with the same issue but in the different direction. My server can only read the message from one single device and no other device a user is connected with.
