### ISSUE TITLE
How to get room names?

### ISSUE THREAD

**Issue by JohnGebbie** [mautrix/go#87]
Thank you for this library. I've just been struggling to get the human readable names of rooms like "General" and "Random".
I think `room.GetStateEvent(event.StateRoomName, "")` is what I need but I'm just getting `nil`.

Here's an example program:
```
package main

import (
	"fmt"
	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/event"
)

func login(client *mautrix.Client, user, password string) (*mautrix.RespLogin, error) {
	return client.Login(&mautrix.ReqLogin{
		Type: "m.login.password",
		Identifier: mautrix.UserIdentifier{
			Type: mautrix.IdentifierTypeUser,
			User: user,
		},
		Password: password,
	})
}

const (
	user = // put username
	password = // put password
)

func main() {
	client, err := mautrix.NewClient("https://matrix.org", "", "")
	resp, err := login(client, user, password)
	if err != nil {
		panic("Failed to log in.")
	}
	client.SetCredentials(resp.UserID, resp.AccessToken)

	response, err := client.JoinedRooms()
	if err != nil {
		panic("Failed to get rooms.")
	}

	// Prints: [!UbWBtSLQIpZcZJsLXn:matrix.org !BVmJKGPchhqhmdbKoq:matrix.org !hMdfRMncIdgqvhSUZK:matrix.org]
	fmt.Println("roomIDs:", response.JoinedRooms)

	for _, roomID := range response.JoinedRooms {
		room := mautrix.NewRoom(roomID)
		// Prints <nil> for each of them :(
		fmt.Println(room.GetStateEvent(event.StateRoomName, ""))
	}
}
```

Any idea of what's wrong? Thank you.

**Comment by tulir** [comment]
Are you sure the rooms have names?

**Comment by JohnGebbie** [comment]
> Are you sure the rooms have names?

Maybe it's not the right thing, but the default rooms on a Element were "General" and "Random", I tried renaming them and creating another room also.

**Comment by JohnGebbie** [comment]
I had the same issue with gomatrix but I found `client.StateEvent(roomID, "m.room.name", "", &content)` works :)

**Comment by tulir** [comment]
Oh huh, I didn't read the code carefully enough. Yeah, `NewRoom` won't do anything other than create a struct which can be used for caching, you can't get data from the server that way. Methods for the API are on Client.
